apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: get-converted-exams-cluster
  region: us-west-2
  version: "1.28"

# IAM settings
iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true
  - metadata:
      name: ebs-csi-controller-sa
      namespace: kube-system
    wellKnownPolicies:
      ebsCSIController: true
  - metadata:
      name: cluster-autoscaler
      namespace: kube-system
    wellKnownPolicies:
      autoScaling: true

# VPC Configuration
vpc:
  enableDnsHostnames: true
  enableDnsSupport: true
  cidr: "10.0.0.0/16"
  subnets:
    public:
      us-west-2a:
        cidr: "10.0.1.0/24"
      us-west-2b:
        cidr: "10.0.2.0/24"
      us-west-2c:
        cidr: "10.0.3.0/24"
    private:
      us-west-2a:
        cidr: "10.0.11.0/24"
      us-west-2b:
        cidr: "10.0.12.0/24"
      us-west-2c:
        cidr: "10.0.13.0/24"

# Node Groups
nodeGroups:
  - name: worker-nodes
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 2
    maxSize: 10
    volumeSize: 20
    volumeType: gp3
    privateNetworking: true
    ssh:
      allow: true
      publicKeyName: your-key-pair # Replace with your EC2 key pair name
    labels:
      role: worker
      environment: production
    tags:
      Environment: production
      Application: get-converted-exams
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEBSCSIDriverPolicy

# Add-ons
addons:
- name: vpc-cni
  version: latest
- name: coredns
  version: latest
- name: kube-proxy
  version: latest
- name: aws-ebs-csi-driver
  version: latest

# CloudWatch logging
cloudWatch:
  clusterLogging:
    enable: ["api", "audit", "authenticator", "controllerManager", "scheduler"]
    logRetentionInDays: 30