apiVersion: v1
kind: ServiceMonitor
metadata:
  name: get-converted-exams-monitor
  namespace: get-converted-exams
  labels:
    app: get-converted-exams
spec:
  selector:
    matchLabels:
      app: get-converted-exams
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
---
apiVersion: v1
kind: Service
metadata:
  name: get-converted-exams-metrics
  namespace: get-converted-exams
  labels:
    app: get-converted-exams
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: get-converted-exams
  ports:
  - name: metrics
    port: 80
    targetPort: 80