apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: get-converted-exams-pdb
  namespace: get-converted-exams
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: get-converted-exams